### ISSUE TITLE
Micro Wave Tel. X Tag error: Tag LC 23105

### ISSUE THREAD

**Issue by kechave** [tristan-sebens/metl#101]
Received the following error when trying to upload Microwave Telemetry X Tag (LC 23105):

Error in value[[3L]](cond) : 
  Error updating TAG_DATA_INSTANT from temporary table:
In decoder$decode_to_db: ODBC failed with error 23000 from \
             [Oracle][ODBC][Ora].

**Comment by KevinSiwicke-NOAA** [comment]
I had the same/similar error with a MT Xtag (RE 23120, though the file is the Argos number (117230): 

Error in value[[3L]](cond) : 
  Error updating TAG_DATA_INSTANT from temporary table:
In : nanodbc/nanodbc.cpp:1710: 23000
[Oracle][ODBC][Ora]ORA-00001: unique constraint (ABLTAG.SYS_C001735021) violated

**Comment by tristan-sebens** [comment]
The only UNIQUE constraint present in the TAG_DATA_INSTANT table (as well as all of the other data tables) is that no tag may have multiple records which occupy the same instant in time (or same time period in the case of aggregate data), suggesting that this error stems from the extracted data having duplicate records. I'll investigate.

**Comment by tristan-sebens** [comment]
Review of the output data revealed that there is in fact a duplicated row:

![Image](https://github.com/user-attachments/assets/5ca6f1b5-e432-44ee-ac63-b11997b31eb5)

The package already has a process by which timestamps which are too close together are bumped apart in order to avoid this exact situation, but upon review I realized that the increment by which these timestamps were separated was too small to make them distinct from one another when imported by the database. I increased this increment from 0.1 s to 1s, and the problem resolved.
