### ISSUE TITLE
error when uploading Star Oddi DST Milli F (tag JS 108)

### ISSUE THREAD

**Issue by kechave** [tristan-sebens/metl#102]
Received the following error when trying to upload Star Oddi DST Milli F (JS 108):

Error in verify_data_directory(d) : 
  The selected directory does not contain the necessary data to proceed.
In addition: Warning message:
In verify_data_directory(d) :
  The selected directory does not show the structure expected by the selected Decoder:

Data file missing or mislabeled. Should match pattern: ^JS\d+\.xlsx and contain fields: Comp.Head(°), Comp.4p(°), Mag.vec(nT)

**Comment by tristan-sebens** [comment]
Error indicates that the `Identifier` child object of the StarOddi DST milli-F `Decoder` object gave a negative response when applied to the data directory for tag JS108. This is typically caused by a mislabeled data-file, but in the case of the StarOddi tags can also be due to mislabeled fields within the data file. However in this case, the copy of this data file which I have did not appear to have any of these problems.

This error could not be replicated. Data was successfully extracted from data directory.

More information is needed to determine the root cause of this error.
