### ISSUE TITLE
move Tag_Type to first column in TAG_DATA_INSTANT

### ISSUE THREAD

**Issue by kechave** [tristan-sebens/metl#111]
Move TAG_TYPE to first column in table TAG_DATA_INSTANT...tables should always open to the Tag Type and Tag Number seen clearly.

**Comment by kechave** [comment]
Same for TAG_DATA_SUMMARY

**Comment by tristan-sebens** [comment]
Table columns rearranged so that TAG_TYPE, then TAG_NUM are always first two columns. Also rearranged timestamp fields to be more orderly.

**Comment by tristan-sebens** [comment]
Turns out I only temporarily reordered the columns. 

Research tells me that the only way to permanently reorder the columns is to recreate the table.

**Comment by tristan-sebens** [comment]
Like issue #114, this will need to be done concurrently with the release of the 0.4 update, so as to minimize disruption.

**Comment by tristan-sebens** [comment]
I now realize that, because of the network of constraints which bind these tables together, in order to perform this change I would have to drop ALL of the tables, then recreate them one by one. 

While this is technically possible, I feel at this time that the risk of breaking the DB system is too great to justify the benefit of reorganizing the DB columns.
