### ISSUE TITLE
Problem installing on RStudio

### ISSUE THREAD

**Issue by jknielsen** [tristan-sebens/metl#34]
Trying to install on RStudio using:

devtools::install_github(repo = "https://github.com/tristan-sebens/metl", upgrade="never")

I received the following error message:
Using GitHub PAT from the git credential store.
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 59/60
  Rate limit reset at: 2024-05-18 00:18:20 UTC

Is this a problem with my computer or RStudio configuration?

**Comment by tristan-sebens** [comment]
Hey Julie,

Documenting our email conversation here for posterity. The "Using GitHub PAT from the git credential store" message suggests to me that your issue is rooted in the authentication behavior of `install_github`, which defaults to using any token stored in the GITHUB_PAT environmental variable. 

I would suggest first clearing this value using a `Sys.unsetenv("GITHUB_PAT")` call, then retry the install. 

Alternatively, you may have some luck setting `auth_token = NULL` in the `install_gihub` command.

**Comment by jknielsen** [comment]
This was an authentication problem on the user end - nothing to do with the metl package. In case it helps someone else with this error, I finally got it working after a first-party GitHub OAuth application (Git Credential Manager) with gist, repo, and workflow scopes was authorized to access my account.

**Comment by tristan-sebens** [comment]
Excellent. Glad you were able to get the package installed, and big thanks for documenting the issue here!
