### ISSUE TITLE
subscript out of bounds

### ISSUE THREAD

**Issue by CindyTribuzio-NOAA** [tristan-sebens/metl#59]
# Set up directory for the specific tag, no folder hierarchy within the directory
tag_data_directory = here::here('C://Users/cindy.Tribuzio/Work/temp_folder/Tagging/metl_testingdata/loading/5728') 

if(!dir.exists(tag_data_directory)) stop("Data directory does not exist")

# Tag set up
meta = 
  data.frame(
    tag_id = "5728",
    tag_type = "ET"
  )

# Read Tag
decoder = metl::decoders$Decoder_Lotek_1300

decoder$decode_to_db(d = tag_data_directory, con = db_conn, meta = meta)

# Resulting Error
Error in `[.data.frame`(dat__, lapply(output_data_field_map$field_list[common_fields],  : 
  undefined columns selected

# Data files
[LTD1300D5728_Day Log.csv](https://github.com/user-attachments/files/16135179/LTD1300D5728_Day.Log.csv)
[LTD1300D5728_Regular Log.csv](https://github.com/user-attachments/files/16135180/LTD1300D5728_Regular.Log.csv)

**Comment by tristan-sebens** [comment]
Hi Cindy,

I think this was due to an error in the documentation. In it's default configuration, the package expects the tag ID # field to be named 'tag_num'. This was originally named 'tag_id', as you have in your code, but was renamed to conform to the ABLTAG DB naming conventions. However, it appears I forgot to update the docs. I've pushed up the change now.

Changing the field name in the `meta` data.frame from 'tag_id' to 'tag_num' should solve your issue.
