### ISSUE TITLE
"NULL"??

### ISSUE THREAD

**Issue by CindyTribuzio-NOAA** [tristan-sebens/metl#61]
Does "NULL" mean success or is that a new issue?
>decoder$decode_to_db(d = tag_data_directory, con = db_conn, meta = meta) 
Note: method with signature ‘Oracle#character’ chosen for function ‘odbcConnectionColumns_’,  target signature ‘Oracle#SQL’.  "OdbcConnection#SQL" would also be valid 
NULL

A separate R question. I ran into a lot of challenges with installing/updating packages. I had to manually remove each of the packages before I could install or update anything. Further, I had to be in 4.3.3 before I could update 'odbc'. (at least that was my chain of events that finally made things work). Any idea why R won't update a package?

**Comment by tristan-sebens** [comment]
Yes, a NULL return indicates a successful transfer!

**Comment by tristan-sebens** [comment]
As to the package updating issues, I have experienced the same frustration. I am not completely sure where this issue comes from, but I think that it has to do with RStudio putting locks on the package directories when they are in use to ensure that they don't get modified. These locks are supposed to be removed once the package is no longer in use, but I think they sometimes get left in place, which means when we try to update them, they appear to be in use and RStudio prevents us from modifying them.

**Comment by CindyTribuzio-NOAA** [comment]
One suggestion, can you add some text that indicates successful upload?

**Comment by kechave** [comment]
I second Cindy's request. 'Successful upload' or something similar would be more intuitive to the user.

**Comment by tristan-sebens** [comment]
Updated code to indicate when an upload has been successful, and to detail how many rows were updated/added
