### ISSUE TITLE
Writing data to `.csv` files

### ISSUE THREAD

**Issue by CindyTribuzio-NOAA** [tristan-sebens/metl#76]
Can file names be more descriptive? Please include tag_type and tag_num in the file name

What is the timestamp in the instant.csv file? Can this be converted to a meaningful value?

There was no summary.csv file for the test tag (ET5728). Can there be some output text that explains why? Or if there are errors.

**Comment by tristan-sebens** [comment]
The `TIMESTAMP` field is a POSIXct timestamp number. This is an advantageous data format because it can specify an instant in time without having to specify a timezone. However, it does have the disadvantage of being completely unreadable to the user. 

In the development version of the package (not released yet) the package now outputs a `FIELD_METADATA` frame, which describes the contents and units of all of the output fields. This will communicate to the user that the `TIMESTAMP` field is a POSIXct timestamp, which will allow them to convert it into a character timestamp in the timezone of their choice. 

However, in the version you are currently using, this output doesn't exist, so there is no documentation about the timestamp format. 

I'll add a note to the README

**Comment by tristan-sebens** [comment]
Character timestamps have now been added to the output `FieldMap` objects, so the POSIXct timestamps will be accompanied by human-readable timestamps, which will automatically be formatted to the timezone of the system decoding the tag data (#67).

**Comment by tristan-sebens** [comment]
To your third point: Not all tags produce all data types, so the `summary` dataset will only be available for tags which produce `summary` data.

I've added a table to the README detailing which tags produce which types of data.

**Comment by tristan-sebens** [comment]
Due to current implementation architecture, it is actually somewhat difficult for the code which saves the output data to know what are the id and tag type values of the current tag.

For now I would recommend simply naming the output directory with the tag id and tag type values. However, I will add this feature to the backlog for potential future implementation.

Feature request recorded in issue #113
